version: '3.8'
services:
  text-api:
    build: {context: ./api, dockerfile: Dockerfile}
    ports: ["5000:5000"]
    volumes: ["./api/recognized_text.txt:/app/recognized_text.txt"]
    environment: ["PYTHONBUFFERED=1"]
    restart: unless-stopped